### ISSUE TITLE
Add emit() to ModuleApiProvider

### ISSUE THREAD

**Issue by JuliaRechkunova** [catberry/catberry#142]

**Comment by pragmadash** [comment]
I think it is not a good idea to give the interface for emitting events. In this case develop receives an ability to emit all events including Catberry-events, like `documentRendered` or `storeLoaded`. It can confuse someone in some cases.

**Comment by JuliaRechkunova** [comment]
I have component Analytics, that can listen eventBus 'analyticsEvent' event and sends events direct to Google Analytics, and another component, from which I want to emit an event like this:
```javascript
this.$context.emit('analyticsEvent', params);
```

There is a better approach?

**Comment by pragmadash** [comment]
I think it is better to register a service in the locator called `analytics` and implement it in two ways: 
* The server-side mock that does nothing
* The client-side interface for `ga` by Google
Register this service as a singleton like this: 
```javascript
catberry.locator.register('analytics`, Analytics, config, true');
```
And then inject it to any component via DI.
```javascript
function Component($analytics) {
  $analytics.send(...);
}
```
In this case, we can even implement the server-side version of the analytics sender later and use it in the isomorphic way.

**Comment by JuliaRechkunova** [comment]
Ok, thanks.
