### ISSUE TITLE
Injection of configuration properties not work in release mode in browser.

### ISSUE THREAD

**Issue by mansurg** [catberry/catberry#143]
In release mode (like this ```$ npm start```) in browser following stuff not work:
```
function MyStore(title, foo) {
  if(this.$context.isBrowser) {
    console.log(title); // undefined
    console.log(foo); // undefined
  }
}
```
But if I add to arguments $ then everything works:
```
function MyStore(title, foo, $) {
  if(this.$context.isBrowser) {
    console.log(title); // Catberry Application
    console.log(foo); // bar
  }
}
```

**Comment by pragmadash** [comment]
As it is said in documentation [here](https://github.com/catberry/catberry/blob/4.7.0/docs/index.md#dependency-injection):
"Please keep in mind that config fields can be injected only side by side with service injections. If you want to inject only config section alone it will not work, use $config injection instead."

That is why the dependency injection does not work for you properly. Try to inject `$config` and access all the sections you want.

**Comment by mansurg** [comment]
Thanks, I must re-read the documentation.
