### ISSUE TITLE
Компоненты

### ISSUE THREAD

**Issue by wormen** [catberry/catberry#154]
Приветствую.
у меня такой вопрос .... я хочу сделать компонент для вставки визуального редактора, но для корректной работы ему нужно задать уникальные атрибуты ID и NAME, хотел передавать данные через атрибут компонента, но не прокатило ... собственно вопрос ... как передать данные в компонент, минуя Store?
В доках я ничего по этому поводу не увидел .... возможно есть какие-то другие варианты, либо я что-то пропустил ...

**Comment by pragmadash** [comment]
Можно пример HTML хотя бы? Со слов мало чего понятно.

Какие данные пытался передавать через атрибут компонента и как это делал (лучше код)?

В компонент минуя Store можно передать данные только в атрибутах при использовании тэга или создания компонента через метод `this.$context.createComponent` ([доки](http://catberry.org/documentation#cat-component-context)).

Еще в компоненте можно реализовать методы, которые выставляют данные, например `setData`  и потом вызывать из другого компонента так `this.$context.getComponentById('id').setData({...})`.

**Comment by wormen** [comment]
да, конечно, вот пример

у меня есть компонент
<p>&lt;cat-editor id=&quot;EditorBlock&quot;&gt;&lt;/cat-editor&gt;</p>

внутри, пока находится только тег textarea(позже будет больше тегов), для которого нужно передать атрибуты ID и NAME через этот компонент

вышеуказанную функцию. я как-то не заметил в доках .... если я правильно понял, то в принципе можно подключать компонент в таком виде какой он сейчас, а дальше вызывать функцию this.$context.createComponent с нужными параметрами, для присвоения атрибутов
я правильно понял?

**Comment by pragmadash** [comment]
Если ты собираешься передавать текст или большие значения через атрибуты компонента, то плохая практика, лучше все-таки реализовать для этого метод в компоненте как я описал выше и выставлять через него. А в методе уже работать с DOM напрямую.

**Comment by wormen** [comment]
нет, через атрибуты я хотел передавать только то, что описал выше, все остальное делать как положено

**Comment by wormen** [comment]
и появился еще вопрос, который имеет прямое отношение к описанному здесь .....
в доках вижу что есть функционал для работы с куками, а как обратиться к сессии которая хранится на сервере, конкретно в Вашем фреймворке?

**Comment by pragmadash** [comment]
В Catberry нет понятия сессии, хорошей практикой работать с такими вещами на API, а туда ходить по токену, который хранится в куке. Так и делает плагин [catberry-oauth2-client](https://github.com/catberry/catberry-oauth2-client).

Catberry это фронт-енд работающий и на сервере и в браузере, это не про сессии.
