### ISSUE TITLE
Сессии

### ISSUE THREAD

**Issue by wormen** [catberry/catberry#157]
В продолжение к #154 раз уж я там ответить не могу ... Вы наверное не так поняли, Oauth в данном случае не поможет, так как есть необходимость хранить сессии на клиенте, соответственно, с ними нужно как-то работать

**Comment by wormen** [comment]
Даже если и через Oauth работать, то как минимум должен быть, ID сессии, который можно было отправить на серверную часть, и там с сессией работать, раз тут нету такой возможности

**Comment by pragmadash** [comment]
Это вы наверное не поняли, в #154 я все доступно объяснил.
