### ISSUE TITLE
Long building bundle.js

### ISSUE THREAD

**Issue by slonofanya** [catberry/catberry#173]
[INFO] catberry - Browser bundle has been built at public/bundle.js (1.12 min)
What i am doing wrong?

May exist some tricks for fixing it?

**Comment by pragmadash** [comment]
I guess you are using Vagrant and a network shared resource for starting Catberry application like you described [here](https://github.com/catberry/catberry/issues/172).

Have you tried the **real** environment and hard drive instead Vagrant and network FS?

**Comment by slonofanya** [comment]
Yeah, it is because the Vagrant and shared folders.
Let's getting rid of them :)
