### ISSUE TITLE
How to change store's state from component action?

### ISSUE THREAD

**Issue by vaseker** [catberry/catberry#175]
Hello!
I have a component with checkbox group, attached to store, which gets data for group generation.
And I want to change url's query parameters (store's state) when selecting that checkboxes. How can I do that in a proper way?

Does it mean I need to manually work with current $context url, make new url, and redirect to it?

Thanks.

**Comment by pragmadash** [comment]
Yeah, you should use `this.$context.location.clone()`, then manipulate using [catberry-uri](https://www.npmjs.com/package/catberry-uri) and then `this.$context.redirect(clonedUri.toString())`.

**Comment by vaseker** [comment]
Ok, thanks!
Forgot about this gorgeous dependency :)
