### ISSUE TITLE
componentsGlob config not working properly.

### ISSUE THREAD

**Issue by ucin** [catberry/catberry#178]
I try to override the component location using `componentsGlob` attribute on `browser.json` & `environment.json`. But it show warning message ` Component "document" not found, blank page will be rendered`  when try to run with `npm run debug-win`.

When I directly override the `COMPONENTS_DEFAULT_GLOB` variable on `ComponentFinder.js` 

from
```javascript
var COMPONENTS_DEFAULT_GLOB = [
		'catberry_components/**/cat-component.json',
		'node_modules/*/cat-component.json'
	]'
```
to 
```javascript
var COMPONENTS_DEFAULT_GLOB = [
		'components/**/component.json',
		'node_modules/*/cat-component.json'
	]'
```

it work as expected.

**Comment by pragmadash** [comment]
Could you show the config you used?

**Comment by ucin** [comment]
Sorry @pragmadash, my mistake. I assign string of array instead of real array to `componentsGlob`.
This works fine for me now.
```javascript
{
  "title": "Catberry",
  "componentsGlob": [
    "components/**/component.json",
    "node_modules/*/cat-component.json"
  ],
  "storesDirectory": "./stores",
  "bundleFilename":"bundle.js",
  "server": {
    "port": 3000
  }
}

```

Thanks.
