### ISSUE TITLE
Webpack implementation

### ISSUE THREAD

**Issue by imShara** [catberry/catberry#184]
Do you have plans to implement webpack compiler to catberry?

**Comment by pragmadash** [comment]
There was an experiment with Webpack maybe six months ago (before 5.0 release). And it ends with the decision that we don't need Webpack as the building engine and everything can be done with browserify [transforms/plugins](https://github.com/substack/node-browserify/wiki/list-of-transforms). Browserify has implementations of server-side modules our of the box it's less monolithic comparing with Webpack.

**Comment by pragmadash** [comment]
BTW, you can add a browserify transformation using [Catberry Plugin API](http://catberry.org/documentation#plugin-api).
