### ISSUE TITLE
Add items to collection without re-rendering existing items

### ISSUE THREAD

**Issue by SergeySidorchuk** [catberry/catberry#185]
I need manage big collection of items. I try to add item in store, assigned to collection component, and call this.context.change(), but I'd like to avoid re-rendering items that were added earlier. How can I do it?

**Comment by SergeySidorchuk** [comment]
I need manage big collection of items. I try to add item in store, assigned to collection component, and call this.context.change(), but I'd like to avoid re-rendering items that were added earlier. How can I do it?

**Comment by pragmadash** [comment]
So, with the current approach you can't do that.

In our project that is based on Catberry we have feeds with infinite scroll. The scroll event updates the store and re-render the whole feed with all items. We still don't have any problems with 300 items in the feed. We just set the limit to 300 in this case. 

Have you tried to implement such application that have performance issues?

**Comment by SergeySidorchuk** [comment]
Yes, we tried to implement SPA view that has 1000 items in collection. Every item is a control with complex template.  We used infinite loop to boost first-time rendering performance. But performance trouble was not fixed.

**Comment by slonofanya** [comment]
Sergey Sidorchuk, please, do not be like hindus. Follow grammar )

**Comment by zarkone** [comment]
that was just rude.

**Comment by pragmadash** [comment]
@SergeySidorchuk IMO it's not a good idea to show 1000 items list to the user. Such task should be solved by filtering, search, or pagination.

**Comment by pragmadash** [comment]
@SergeySidorchuk New Catberry 6.0.0 release has diff/patch approach you were asking for. https://github.com/catberry/catberry/releases/tag/6.0.0
