### ISSUE TITLE
Pass data from parent component to its childrens

### ISSUE THREAD

**Issue by imShara** [catberry/catberry#187]
E.g. Is there method to pass data from `post-list` component, which make API request to it's childrens, `post-item` components, which displays data.

cat-post-list
``` jade
h2 Posts
each post in posts
  cat-post-item
```

cat-post-item
``` jade
article
  h3 #{post.title}
  p #{post.content}
  a(href="/posts/#{post.id}") Read more
```

**Comment by pragmadash** [comment]
Passing data is not a right solution in this particular case.
You can set `data-index` property to the list's item component and link it with `cat-store` where the list is.

For example, `render` method in the item component:
```javascript
Item.prototype.render = function () {
  var index = Number(this.$context.attributes['data-index']);
  return this.$context.getStoreData()
    .then(function (list) {
      return list[index];
    });
};
```

The example can be found [here](https://github.com/catberry/catberry-benchmarks/blob/master/catberry/catberry_components/users/template.jade).

**Comment by pragmadash** [comment]
The general idea that all data should be shared via stores, and you can only set some attributes to the nested components.

**Comment by imShara** [comment]
Hm, thanks. I think here is huge perfomance issue, which solved by data passing in react-like web components. And this isn't break store links, because nested components updates when root component data in store changes.

**Comment by pragmadash** [comment]
There is no any performance issues here, because Catberry.js deals with it in a right way. There will be no multiple `load` calls of any Store this way.

**Comment by imShara** [comment]
> There is no any performance issue here
Even if store data outdate while rendering?

**Comment by pragmadash** [comment]
By default it is cached for 60 seconds or you can control it using [`$lifetime`](http://catberry.org/documentation#store-interface) property of the store.

If you have a lot of concurrent queries for store loading, then only the first will be served using store's `load` method and others will wait and receive the same answer. The answer will be cached for $lifetime and requesting data again does not occur `load` method call again.

**Comment by pragmadash** [comment]
You can see the feed developed using such approach [here](http://moscow.flamp.ru/topics). Does it have poor performance?

**Comment by imShara** [comment]
It have enough perfomance, but I think this can be done better than getting all store data for each post with function and return one array item from it. I will make some benchmarks then. Thanks.

**Comment by pragmadash** [comment]
@imShara It does not copy the data array, it just have an access to the array and take an item by an index. What could be more efficient? If you use something like "parameter passing approach" it costs more than just to have an access to the data array.

Anyway if you need to pass just a few short fields to the nested components you can use tag attributes.
