### ISSUE TITLE
query parameters

### ISSUE THREAD

**Issue by wormen** [catberry/catberry#189]
у меня собственно вопрос ...
возможно ли как-то сделать, чтобы роутер не реагировал на query parameters при переходе по ссылке, но при этом, чтобы их можно было получить в приложении?

**Comment by pragmadash** [comment]
Нет.
А как приложение должно вообще узнать что они поменялись если роутер не должен реагировать?

**Comment by wormen** [comment]
так добавление/изменение GET параметров, это ведь далеко не всегда другая страница, в некоторых ситуациях они используются исключительно для служебных целей. и к роуту не относятся

как пример, UTM метки

вопрос то собственно к тому, что у меня есть приложение, где заранее неизвестно наличие и кол-во GET параметров, а роутер на текущий момент на них реагирует

может есть какой-то вариант чтобы можно было вынести в конфиг настроечку, "реагировать / не реагировать на GET параметры" ?

**Comment by pragmadash** [comment]
Прости, телепаты были в отпуске, сейчас я понял что речь идет об опциональных query параметрах в URI и то что у тебя 404 при их отсутствии/присутствии лишних.

Я не знаю какой фреймворк ты используешь но в Catberry уже очень давно query параметры опциональны и ошибка 404 не происходит при отсутствии каких либо из них. Поэтому UTM метки отлично работают. Об этом кстати написано в документации, целый [раздел](http://catberry.org/documentation#url-with-any-query-parameters).
