### ISSUE TITLE
Do research on using diff/merge algorithm for the entire document renderer

### ISSUE THREAD

**Issue by pragmadash** [catberry/catberry#190]
Now Catberry uses diff/merge for HEAD element only.
We can try to use it for everything and compare the results.

For example, there is an awesome lightweight implementation https://github.com/patrick-steele-idem/morphdom

We can replace the existed engine with that package and apply it to other components.

**Comment by pragmadash** [comment]
https://github.com/catberry/catberry/tree/feature/%23190-diff-patch-rendering

**Comment by pragmadash** [comment]
Works great. I published it as catberry@6.0.0-dev on NPM.

**Comment by vaseker** [comment]
+1 it works!

**Comment by pragmadash** [comment]
The feature is published as a stable release 6.0.0.
