### ISSUE TITLE
Do not remove script, style, link tags while patching HEAD element

### ISSUE THREAD

**Issue by pragmadash** [catberry/catberry#191]
It causes problems with lazy loaders of third-party libraries.

**Comment by pragmadash** [comment]
We need a feature from morphdom at first. https://github.com/patrick-steele-idem/morphdom/pull/8

**Comment by vaseker** [comment]
Em. I think its broken now.. Maybe because of morphdom.
You can see that on http://netbuyer.ru: its <head> element <title> modifies for each page jump, and its removes google font. So I used dirty method: fixed <link> in template...

**Comment by vaseker** [comment]
Ahh. Its tagged as 6.1.1. Im using old Catberry.
