### ISSUE TITLE
Microsoft Edge fails executing Catberry's client-side JavaScript bundle

### ISSUE THREAD

**Issue by pragmadash** [catberry/catberry#192]
It seems like Microsoft Edge has a bug in its JavaScript parser or virtial machine. It just doesn't open any website where Catberry's bundle.js is included.

**Comment by pragmadash** [comment]
I've started a discussion on Microsoft Tracker http://answers.microsoft.com/en-us/windows/forum/apps_windows_10-msedge/microsoft-edge-cant-load-any-website-built-using/10f943d6-c970-423d-aba3-97cd31c81089?tm=1439991037162

**Comment by vaseker** [comment]
+1 got same behavior
Have you checked location api changes in edge? 
P.S. You can open cat-projects by opening edge's debug tools and refresh page few times.

**Comment by pragmadash** [comment]
This is definitely a bug in MS Edge and it's connected with JavaScript parsing or initialization. Catberry's JavaScript code does not even start executing. So, the problem is not related to any API. I have a source in MS who said that they are investigating the issue and promised to fix it as soon as possible.

**Comment by pragmadash** [comment]
BTW, Internet Explorer in Windows 10 Technical Preview builds just crashes loading pages built with Catberry. I'm sure it's not a Catberry's issue.

**Comment by vaseker** [comment]
Heh. It 100% works if you stuck on cat-project page, **open dev tools**, then **focus on address bar and press enter** (no F5, no ctrl+r. focus and enter).
![cat-edge](https://cloud.githubusercontent.com/assets/1942271/9505539/84b5f702-4c5c-11e5-8645-f279a1bca1a8.PNG)

**Comment by pragmadash** [comment]
@vaseker you mean I should tell all 3 million users of the web-site built using Catberry that they have to open MS Edge Dev Tools before going to the web-site? Do you offer this solution?

It does not matter that you are able to open the web-site using dirty hacks. It should work like in other browsers. Otherwise it is a bug and does not work.

**Comment by vaseker** [comment]
No. It's just a way to load site. It must be fixed)
27 авг. 2015 г. 9:42 пользователь "Denis Rechkunov" <
notifications@github.com> написал:

**Comment by vaseker** [comment]
It seems fixed in 10532 build

**Comment by pragmadash** [comment]
@vaseker So, how can I check it? There is only 10240 build on http://modern.ie and it fails installing updates with error.

**Comment by vaseker** [comment]
This build should be on torrents. I received this update via microsoft
insider program.
1 сент. 2015 г. 9:55 пользователь "Denis Rechkunov" <
notifications@github.com> написал:

**Comment by pragmadash** [comment]
>This build should be on torrents.

I am not sure this is a legal way to install the build :laughing:

**Comment by vaseker** [comment]
Im not sure too, but these builds usually distributes as clean MSDN iso
without illegal activation

**Comment by pragmadash** [comment]
So, could you tell me how to get a notification when this build will be in production and we will be able to close the issue.

**Comment by vaseker** [comment]
Deal.

**Comment by pragmadash** [comment]
I mean, I'm asking for the way to receive the notification from Microsoft somehow. But the information from is useful too.

**Comment by vaseker** [comment]
I dont know this way)

Possible it will available not less than SP1, so you cannot skip its announcement.
Or we can compare edge's versions on 10240 & 10532, then search diff KB, and watch for its public deployment as standalone update.

**Comment by vaseker** [comment]
It works for now on fully updated win 10.

**Comment by pragmadash** [comment]
@vaseker Could you write here an identifier of update package? Just for confirmation.

**Comment by vaseker** [comment]
Nope, I can't detect it.

**Comment by pragmadash** [comment]
Anyway, I'm closing the issue then.
