### ISSUE TITLE
Browserify errors are not shown by Catberry

### ISSUE THREAD

**Issue by pragmadash** [catberry/catberry#193]
If `./browser.js` or other browser-side script is broken Catberry just hangs up on building browser script and does not respond.

**Comment by slonofanya** [comment]
I think it bad idea, Cadbury should write down these errors to logs (or maybe to console), shows empty content in browser and DO NOT hangs up. It is annoying now.

**Comment by pragmadash** [comment]
@slonofanya I guess you confused the issue with something else.
It's about a process of building bundle.js when you start `node build.js` in a project. Now if you have a syntax error in the `browser.js` file, for example, it will not display the error in the console and just hang up the process.

>shows empty content in browser and DO NOT hangs up. It is annoying now

What do you mean by that? Is it about server-side rendering or something?
