### ISSUE TITLE
динамические компоненты

### ISSUE THREAD

**Issue by wormen** [catberry/catberry#194]
приветствую
у меня вопрос ...
есть ли возможность создавать конструкции для так называемых "динамических компонентов". чтобы было более понятно, описываю пример.

например, у меня есть модульная структура приложения, т.е. для каждого раздела есть свой компонент, и чтобы не городить в основном компоненте конструкцию вида if/else. сделать что-то вида (возможны другие варианты)

```
<component  id="{{componentID}}" name="{{componentName}}" store="componentStore"/>
```

**Comment by markuplab** [comment]
```
<cat-{{component}}></cat-{{component}}>
```

**Comment by wormen** [comment]
@markuplab я так понял. остальные параметры присваиваются как в моем примере

**Comment by wormen** [comment]
непосредственно компоненты при таком подходе нормально заводятся, а вот сторы нет
подскажет кто как это можно решить?

**Comment by pragmadash** [comment]
@wormen Например, правильно использовать название `cat-store` вместо `store`.

**Comment by pragmadash** [comment]
@wormen В этом репозитории все issues обрабатываются исключительно на английском языке. Issues на других языках будут игнорироваться и немедленно закрываться.
