### ISSUE TITLE
Proper way to listen component's bound event

### ISSUE THREAD

**Issue by vaseker** [catberry/catberry#196]
Is there a proper way to bind handler for component `bound` event?
I did that:
```javascript
function Component() {
	this.$context.on('componentBound', function (data) {
		if (data.element === this.$context.element) {
			this._loaded();
		}
	}.bind(this));
}
```
but these listeners lives global and doesn't self-destructs.

**Comment by vaseker** [comment]
Better version:
```javascript
Component.prototype.bind = function () {
	this._loaded();
        return {};
}
```

**Comment by pragmadash** [comment]
I am not sure I got you right. Why do you need `componentBound` handler?

Actually when a component's method `bind` finishes its execution (or promise which is returned by method resolves) it is the moment when "component is bound". Why do you need to use additional event listening?

**Comment by vaseker** [comment]
Its useful for client modules initialization like size recalculations, resize bindings, etc.
Updated, full, example is:
```javascript
GoodsSlider.prototype.bind = function () {
	this._loaded();
	window.addEventListener('resize', this.__onResize, false);
	return {
		click: {
			'.goods-slider__control_prev': this._prev,
			'.goods-slider__control_next': this._next
		}
	};
};

GoodsSlider.prototype.unbind = function () {
	window.removeEventListener('resize', this.__onResize, false);
};
```

**Comment by vaseker** [comment]
Im just expected way like
```javascript
Component.prototype.bind = function () {
  return {
    bound: {
      $component: this._loaded
    },
    click: {
      '.class': this._method
    }
  }
};
```

**Comment by pragmadash** [comment]
Okay, what solution are you looking for?

>```javascript
GoodsSlider.prototype.bind = function () {
	this._loaded();
	window.addEventListener('resize', this.__onResize, false);
	return {
		click: {
			'.goods-slider__control_prev': this._prev,
			'.goods-slider__control_next': this._next
		}
	};
};
GoodsSlider.prototype.unbind = function () {
	window.removeEventListener('resize', this.__onResize, false);
};
```

This example seems right and it works fine using current module API. What's exactly the issue?
Should I close it or something?

**Comment by vaseker** [comment]
Thanks. I think that my solution may be better using `return { event: { elem: handler } }`

Is it possible to implement that logic like [this example](https://github.com/catberry/catberry/issues/196#issuecomment-136151528)?

**Comment by pragmadash** [comment]
IMO it should not look like this. Because there are only DOM events in the events map and it seem transparent for everyone. So, everything else should be in a component's code like you described using `bind`/`unbind`.

I mean, adding such "magic hints" we are increasing the complexity of the framework. The documentation becomes bigger, there are more things to remember for developers and so on. I would never expect that from Catberry.
