### ISSUE TITLE
How to get state of Store in handleSomeAction

### ISSUE THREAD

**Issue by slonofanya** [catberry/catberry#198]
I have:
```
    load: function () {
      return Promise.all([some_tasks]).then(function (data) {
              return {
                property: property,
                isInPortfolio: false
              };
            });
    },
    
    handleSomeAction: function () {
        this.$context.state.isInPortfolio; // <--- is undefined
        this.$context.changed();
    }
```

And in component (Store defined in <cat-component/>):
```
this.$context.sendAction('SomeAction')
```

How to manipulate of state in Store handle methods?

**Comment by pragmadash** [comment]
You can access store's state by using
```javascript
this.$context.store
```
as it's described in [docs](http://catberry.org/documentation#store-context)

**Comment by slonofanya** [comment]
I updated code

**Comment by pragmadash** [comment]
You mean you'd like to use data returned from `load` method? In this case you should save it by yourself in `this._isInPortfolio`, for example.
State is a different thing – it's a set of parameters from URI linked with the store.

**Comment by slonofanya** [comment]
Ok. I've got. Thanks.
