### ISSUE TITLE
sessions

### ISSUE THREAD

**Issue by wormen** [catberry/catberry#201]
documentation did not meet with the references about the work sessions,
do you plan to add functionality to work with the sessions?

since the framework is only through the API ... in my opinion not the best solution when data is to be in session, to drive them to API

**Comment by slonofanya** [comment]
If you mean authorization session - it must be saved on API(Back-End) side, because of security

**Comment by wormen** [comment]
@slonofanya 
I did something about the written authorization?
I personally, for example, you just need to store the intermediate data in the session

**Comment by slonofanya** [comment]
Most of the time the site will operate as a SPA, in a browser, and session does not make sense. You can store data in localstorage or Stores )

**Comment by wormen** [comment]
@slonofanya These facilities are not suitable, as part of the data should not be available to the user

**Comment by pragmadash** [comment]
That's not an issue for the framework but for your application's architecture. Closing.
