### ISSUE TITLE
Communication between components and more problems

### ISSUE THREAD

**Issue by mass3ff3ct** [catberry/catberry#205]
Приветствую. Прошу прощения, что на русском, тяжело корректно сформулировать.
Я озвучу проблемы и приведу несколько примеров того, как можно было бы их решить (ИМХО)
##### Проблема 1. Связи между компонентами.
Предположим имеется универсальный компонент выбора из списка, который ничего не знает о Хранилищах. Так же имеется форма, которая использует этот список. Каким образом можно заставить реагировать форму на изменение списка?
Моё видение:
```
//universal component
function bind() {
   var self = this;
    return {
     'select .mySelect': function () {
         // code
         self.emit('select')
     }
   };
}

// parent component
function bind() {
   retun {
     '@universalComponent select': function () {
         // universalComponent - attr "cat-name" 
         // handler on emit universal component
     }
   }
}
```
Прошу заметить, что emit распространяет событие только на своего родителя, и выше пойти не может.

##### Проблема 2. Лёгкий доступ к вложенным компонентам
Есть всё та же форма и универсальный выбор из списка. Как из формы получить выбранное значение в списке? 
Было бы хорошо увидеть такое:
```
// universal component
function getSelectItemId() {
   this.mySelectElement.val()
}

// parent component
function getDataAndSave() {
   var selectedItem = this.childByName['universalComponent'].getSelectedItemId();
   this.save(...)
}
```

##### Проблема 3. Подписка на изменение конкретного хранилища
Например, есть сервис User. Как мне подписаться на change хранилища CurrentUser, что бы обновить свой сервис ? Использовать User в CurrentUser - размытие логики как по мне.

**Comment by pragmadash** [comment]
**Проблема 1**. Обычно такой компонент сам подписывается на все возможные события внутренних элементов таких как select#select. Затем он дает возможность подписаться на эти события извне. Как это делать – на усмотрение разработчика компонента, это может быть EventEmitter или просто присваивание обработчика события снаружи (родительским компонентом). Такой способ обработки событий – основа идеологии фреймворка об изолированности веб-компонентов.

```javascript
function UniversalSelect() {

}
UniversalSelect.prototype.bind = function () {
  return {
    'select': {
      'select.mySelect': this._onSelect
    }
  };
}
UniversalSelect.prototype._onSelect = function (e) {
  // here can be an additional logic or emitter.emit('select');
  this.onSelect(e);
};
UniversalSelect.prototype.onSelect = function () {
  // empty stub by default, can be assigned externally
};
```

**Проблема 2**. Вся коммуникация между компонентами должна производится по ID, потому что один компонент может быть в нескольких экземплярах. Для этого есть [методы](http://catberry.org/documentation#cat-component-context):
```javascript
this.$context.getComponentById(‘id’); // gets other component by ID
this.$context.getComponentByElement(domElement); // gets other component by DOM element
```
Реализация получения выбранного элемента опять же должна находиться в самом компоненте выбора. Этот компонент реализует публичный метод, который вызывается снаружи другими компонентами. Такой подход и есть сама суть веб-компонентов.

```javascript
var innerSelect = this.$context.getComponentById(‘innerSelectId’);
var selectedValue = innerSelect.getCurrentSelection();
```

По [этой ссылке](https://drive.google.com/file/d/0B6-MNusEpiCDVGczSVlOM25UVG8/view?usp=sharing) можно найти рекомендации как проставлять ID компонентам, чтобы не было коллизий.

**Проблема 3**. Не понял вопроса, что за сервис User?
Все данные, которые как-то зависят от параметров в URI должны предоставляться сторами. Сторы [могут указывать зависимости](http://catberry.org/documentation#store-context) друг от друга. Если меняется один, то сработает изменение другого.

**Comment by mass3ff3ct** [comment]
##### Проблема 3. Вопрос снят. Жесткую связь с URI я не учел)

Спасибо за "Организация проектов на Catberry". Я думаю неплохо было отобразить это в документации, и так же ваши решения для моих проблем (можно в рубрике Best Practices). Всё таки здесь другая архитектура, которую надо прочувствовать, и с ходу её не освоишь без разжевывания вопроса.

**Comment by pragmadash** [comment]
Я планирую сделать такой раздел и перевести документ на английский, пока нет времени на это все.
