### ISSUE TITLE
Pointerevents

### ISSUE THREAD

**Issue by vaseker** [catberry/catberry#207]
Does Catberry have [pointerevents](https://w3c.github.io/pointerevents/) support?
I tried following code but it doesnt work.
```javascript
Menu.prototype.bind = function () {
	return {
		pointerup: {
			'.i_arrow': this.clickFolder
		}
	}
};
```

**Comment by pragmadash** [comment]
It seems like this is just a draft and event [not supported](http://caniuse.com/#feat=pointer) by browsers except IE.

How did you check these events?

**Comment by vaseker** [comment]
Yep, Im checking its wrong. Stupid question.
