### ISSUE TITLE
Empty this.$context.state when use = and & in value

### ISSUE THREAD

**Issue by reenko** [catberry/catberry#210]
Bug when did I use '=' and '&' in value.

In routes.js 
```
page?what=:what[store/Name]
```

When did I load store
``` this.$context.state === {}  ```
state.what - is undefined

URL: page?what=%3Dtes

**Comment by pragmadash** [comment]
Why are you using quote marks around the store name?

```
page?what=:what[store/Name]
```
is the correct value.

**Comment by reenko** [comment]
Sorry, no quote around the store name.

**Comment by pragmadash** [comment]
As I got it right the route rule is `page?what=:what[store/Name]` and the URI is `page?what==test`?
In this case, the correct behaviour is not to parse the value, because `=` is a querystring value separator.

**Comment by reenko** [comment]
I did pull request https://github.com/catberry/catberry-uri/pull/7 for fix this bug.

**Comment by reenko** [comment]
Please, see this example. I reproduce this problem.

**routes.js**
```javascript
module.exports = [
	'/?what=:what[' +
		'Main' +
	']'
];
```

**cat-store**
```javascript
Main.prototype.load = function () {
	return {
		what: this.$context.state.what
	};
};
```

**cat-component / js**
```javascript
SearchForm.prototype.render = function () {
	return this.$context.getStoreData();
};

SearchForm.prototype.bind = function () {
	return {
		form: {
			submit: this._handeSubmit
		}
	};
};

SearchForm.prototype._handeSubmit = function (event) {
	var input = this.$context.element.querySelector('input');
	this.$context.redirect('/what=' + input.value);
}
```

**cat-component / hbs**
```javascript
<form>
	<input type="text" name="what" placeholder="Search" autocomplete="off">
</form>
</br>
{{#if what}}q: {{what}}{{/if}}
```

**Comment by reenko** [comment]
For example I run this project on my server. 

http://cat.malum.ru:3000/?what=asd - it's ok
http://cat.malum.ru:3000/?what=%3Dasd - isn't ok

**Comment by pragmadash** [comment]
Are you sure that you updated Catberry to 7.0.3? Because [this](https://github.com/catberry/catberry/blob/develop/test/cases/lib/providers/StateProvider.json#L316-L335) unit test repeats exactly your situation.

**Comment by pragmadash** [comment]
Tried your code, everything works for me. So, seems like it's not a Catberry's issue this time.

**Comment by pragmadash** [comment]
I noticed a mistake in this part of code
```javascript
this.$context.redirect('/what=' + input.value);
```

It should be '?' before what like:
```javascript
this.$context.redirect('/?what=' + input.value);
```
