### ISSUE TITLE
Route parameter name with dot

### ISSUE THREAD

**Issue by chetverikov** [catberry/catberry#215]
if you specify the name with dot, the argument not passed to this.$context.state

```
// in route
[
    "/companies?bill.average=:bill.average[Filters/List]"
]

// in store Filters/List
this.$context.state['bill.average'] === undefined
```

**Comment by pragmadash** [comment]
Such names for parameters are not allowed and there is wrong a regular expression in the docs. The correct one is `[$A-Z_][\\dA-Z_$]*` like for JavaScript variables. I will fix the docs then.
