### ISSUE TITLE
Replace/remove jshint

### ISSUE THREAD

**Issue by pragmadash** [catberry/catberry#219]
The maintainers released a minor version that broke all catberry builds. And they still have not released a fix for a month already. Need to remove jshint from all catberry projects, maybe replace with something else.

**Comment by pragmadash** [comment]
Solved by 2244814875e84364512eae0393506cbb8deda511

**Comment by markuplab** [comment]
I think you also can remove jscs, because eslint support code style checking features.

**Comment by pragmadash** [comment]
I did, have you seen the commit? :)
