### ISSUE TITLE
Replace log4js with another logger

### ISSUE THREAD

**Issue by pragmadash** [catberry/catberry#222]
Looks like [log4js](https://github.com/stritti/log4js/commits/master) project is dead. We need to pick another one as a logger.

**Comment by vaseker** [comment]
Winston is pretty old and slow. Maybe you should use `bunyan`?

**Comment by vaseker** [comment]
Winston is pretty old and slow. Maybe you should use `bunyan`?

**Comment by pragmadash** [comment]
Agree, we need to consider other alternatives, I found a nice comparison here https://strongloop.com/strongblog/compare-node-js-logging-winston-bunyan/

Also, you can vote for a logger here https://twitter.com/catberryjs/status/702793127053160448

**Comment by pragmadash** [comment]
Performance comparison https://www.loggly.com/blog/a-benchmark-of-five-node-js-logging-libraries/

**Comment by pragmadash** [comment]
100% of [votes](https://twitter.com/catberryjs/status/702793127053160448) are for Bunyan. Apparently, we choose it.

**Comment by pragmadash** [comment]
I turned out that Bunyan uses `util` and `stream` modules even for browser bundle which adds strong overhead. Let's keep Bunyan as a new logger anyway, but need to contact the author and ask for the optimization.

| Version | Build Time, sec | Bundle Size, bytes | Gzipped Size, bytes |
|------------|----------------|------------------|-------------------|
8.0 + Custom | 4.18 | 102105 | 25322
8.0 + Bunyan | 7.79 | 235484 | 65116

**Comment by pragmadash** [comment]
Asked maintainers about the size https://github.com/trentm/node-bunyan/issues/366

**Comment by pragmadash** [comment]
Also found an error in Safari, sent a PR https://github.com/trentm/node-bunyan/pull/367

**Comment by pragmadash** [comment]
I decided to separate logger service from the Catberry core and create several adapters for different loggers including Bunyan, we can't include such huge piece of code into the Catberry's bundle by default.

CLI will generate examples that use stupid light-weight console logger by default.

**Comment by pragmadash** [comment]
Implemented a very simple console logger as a stock solution for the CLI templates. https://github.com/catberry/catberry-logger
