### ISSUE TITLE
Autogenerate components' ID

### ISSUE THREAD

**Issue by pragmadash** [catberry/catberry#246]
Currently, Catberry has a requirement for all components to have unique IDs across the whole page. It can be annoying for developers to invent ID every time they use a custom tag. We can autogenerate human-readable IDs somehow using some rules.

Each ID should contain a parent component ID, current tag name and maybe sequence number in case it's a list item. We need to invent a reliable rule.

**Comment by chetverikov** [comment]
:+1:

**Comment by pragmadash** [comment]
Maybe we can further and invent something to get rid of those IDs at all. I need some time to think about it.

**Comment by pragmadash** [comment]
The bundle size is increased a little bit. For instance, Hello world app:

```
-rw-r--r--   1 pragmadash  staff  28009 Apr 12 18:21 bundle.js.gz
-rw-r--r--   1 pragmadash  staff  27405 Apr 12 18:24 old.bundle.js.gz
```

But it's still fine and I guess not specifying component IDs will shrink the bundle.js because of shorter templates.
