### ISSUE TITLE
.changed() во вложенных компонентах

### ISSUE THREAD

**Issue by KleinMaximus** [catberry/catberry#248]
Приношу извинения за русский язык.

Например, у нас на странице отображается список, и к каждому элементу прикреплена кнопка "Нравится", при нажатии на которую нужно отправить запрос к API о действии пользователя и заменить кнопку на текст "Вам нравится". Я понимаю, как это сделать, когда мы находимся на странице подробного описания элемента списка, где только одна такая кнопка, и сам компонент связан с нужным нам Store.

Но что делать, когда элементов много? В этом случае Store будет "хранить" именно список, и при запуске .changed() нам придется перерисовывать весь компонент списка, хотя нужно поменять только один из элементов.

Если в цикле выводить список в виде вложенных компонентов, то возникает вопрос, к каким Store привязывать эти компоненты.

**Comment by chetverikov** [comment]
Как вариант вы можете сохранять id сущности в html и после клика в обработчике отправлять запрос с нужными вам параметрами

```javascript

handleClick(event) {
  const id = $(event.target).data('id');
  this.$context.sendAction('likeIt', {id});
}

```

**Comment by reenko** [comment]
Вставлю свои пять копеек. 

Можно использовать **индекс элемента**.
Есть store в котором хранится список сущностей, например список новостей и соответственно лента новостей привязана к List, а все отдельные новости так же привязаны в List и знают свой индекс в нем.

Получается когда ты в компоненте отдельной новости делаешь  getStoreData(/* List */), то надо просто взять по индексу(передается через атрибут) нужное значение. 

**Обновление стора**
1) Пользователь ничего не заметит, даже если обновится весь список, потому что фраймворк патчит страницу и то что не изменилось останется неизменным. 

2) Можно ручками изменить данные которые лежат в сторе, правда для этого надо их сначала сохранить, не забывать очищать и быть аккуратным. Если надо могу написать подробнее.

**Comment by KleinMaximus** [comment]
Меня больше интересовало именно обновление Store.

> Обновление стора
1) Пользователь ничего не заметит, даже если обновится весь список, потому что фраймворк патчит страницу и то что не изменилось останется неизменным.

> 2) Можно ручками изменить данные которые лежат в сторе, правда для этого надо их сначала сохранить, не забывать очищать и быть аккуратным. Если надо могу написать подробнее. 

Т. е., предлагается в прямо в Action отправить запрос к API, получить ответ, ручками обновить данные в Store, а потом запустить .changed(). Я так понял?

**Comment by chetverikov** [comment]
да, вызываем sendAction() -> делаем запрос на сервер -> при успешном запросе делаем changed
Ничего ручками менять не надо changed() заставить store перезапросить данные с API, т.е. обновятся все зависящие компоненты, которы в свою очередь перезапросят данные из store

**Comment by KleinMaximus** [comment]
> да, вызываем sendAction() -> делаем запрос на сервер -> при успешном запросе делаем changed
Ничего ручками менять не надо changed() заставить store перезапросить данные с API, т.е. обновятся все зависящие компоненты, которы в свою очередь перезапросят данные из store

Мягко говоря, загружать заново с сервера весь список ради изменения только статуса элемента мне кажется не самым экономным вариантом :(

**Comment by chetverikov** [comment]
Тогда не загружайте, кэшируйте результат первой загрузки и разруливаете изменения в store

**Comment by KleinMaximus** [comment]
> Тогда не загружайте, кэшируйте результат первой загрузки и разруливаете изменения в store

А как в этом случае мне сообщить компоненту, что данные изменились?

**Comment by reenko** [comment]
@KleinMaximus  вызвать this.$context.changed();
в load () должна быть проверка, что надо просто вернуть закэшированные данные и не делать запрос в API, т.е. надо проверить что это та же лента/пользователь/_параметры которые отсылались не изменились_

> Handlers can be used to submit data to a remote resource here or simply change the state within the store – in which case, you would have to emit your own changed event via this.$context.changed().

**Comment by reenko** [comment]
@KleinMaximus  примерно вот так
https://gist.github.com/reenko/7d15f851df54ab264ca63280d7909b49

**Comment by KleinMaximus** [comment]
Большое спасибо!
