### ISSUE TITLE
Add new methods for getting components by class

### ISSUE THREAD

**Issue by reenko** [catberry/catberry#261]
Catberry has methods `this.$context.getComponentById` and  `this.$context.getComponentByElement`

May be add new method `this.$context.getComponentByClassName`

**Comment by pragmadash** [comment]
I would try to keep DOM-like API for that:

* `this.$context.queryComponentSelector('selector')`
* `this.$context.queryComponentSelectorAll('selector')`
* `this.$context.getComponentsByTagName('tag-name')`
* `this.$context.getComponentsByClassName('class-name')`

All the methods just use underlying DOM-method to query an element and then `this.$context.getComponentByElement(element)` to return a component.

**Comment by pragmadash** [comment]
Also, It's needed to add tests and update the docs.

**Comment by pragmadash** [comment]
In the server-side environment all the methods should be replaced with stubs which always return `null`.

**Comment by reenko** [comment]
I think the methods must be linked to element, for example: 
this.$context.**element**.getComponentsByClassName('class-name')

**Comment by pragmadash** [comment]
I'd add a flag as the second parameter to all search-related functions.
For instance: 
```javascript
this.$context.queryComponentSelector(‘.class’, true); // finds components inside the current one
this.$context.queryComponentSelector(‘.class’); // finds components globally on the page
```

**Comment by slonofanya** [comment]
I propose the following: 
```
this.$context.queryComponentSelector(‘.class’, this); // finds components inside the current one
this.$context.queryComponentSelector(‘.class’, anyOtherComponent);  // finds components inside the some other component
```

**Comment by pragmadash** [comment]
@slonofanya makes sense, let's do it then. What do you think, @reenko?

**Comment by reenko** [comment]
@slonofanyag good idea! I will use it
