### ISSUE TITLE
Can't find descendant component in bind method

### ISSUE THREAD

**Issue by pragmadash** [catberry/catberry#268]
```javascript
bind() {
  const nested1 = this.$context.queryComponentSelector(NESTED_SELECTOR, this);
  const nested2 = this.$context.queryComponentSelector(NESTED_SELECTOR);
}
```
In the second case it's `null` for some reason.

**Comment by reenko** [comment]
```
bind () {
    const element1 = this.$context.element.querySelector(NESTED_SELECTOR);
    const nested1 = this.$context.getComponentByElement(element1); // it's ok

    const element2 = window.document.querySelector(NESTED_SELECTOR);
    const nested2 = this.$context.getComponentByElement(element1); // null
}
```

**Comment by pragmadash** [comment]
So far, I can't reproduce the issue, we have unit tests for that [here](https://github.com/catberry/catberry/blob/develop/test/browser/DocumentRenderer.js#L1156-L2017).

The only reason I can guess here can be related to the `bind` method call order. The rendering/bind order is the [DOM Breadth-First traversal order](https://en.wikipedia.org/wiki/Tree_traversal#Breadth-first_search). That means if there are components which are higher in the DOM and you're trying to find them in the descendants it might not work probably because those components can be not registered yet (**need to check this theory**). I'm gonna check it ASAP. And again we have unit-tests for this case.

But anyway it does not explain how the same descendant component can be found from the current component relatively and can't be found globally. That's really weird behavior, that I can't reproduce as well.  IMO opinion it's only possible when you `this.$context.createComponent('cat-some')` and it happens inside the component which is not attached to the DOM.

I'll fix this bug as soon as I invent the unit-test to reproduce the issue. @reenko your help is appreciated.

**Comment by reenko** [comment]
Wow! I reproduce this bug only with `this.$context.createComponent()`, I attach all components in zip-file. (fork from catberry-hello-world-handlebars)

In `Document.js` 
```
this.$context.createComponent('cat-hello-world', {'cat-store': 'Main' })
	.then(element => {
		window.document.body.appendChild(element);
	});
```

In HelloWorld.js
```
const b1 = this.$context.queryComponentSelector('.js-button', this);
const b2 = this.$context.queryComponentSelector('.js-button');

console.log(b1, b2); // b1 !== b2 and b2 === null
```
[catberry_components.zip](https://github.com/catberry/catberry/files/245307/catberry_components.zip)

**Comment by pragmadash** [comment]
I'm not sure if we can do anything with that. This component is not a part of the DOM (because it's created using `createComponent` method). Its `bind` method is called immediately after all nested components are bound but it's still not able to search for nested components globally because they are not a part of the DOM as well, therefore relative search works.

As for me, I would expect this behavior. As I got it right the relative search solves the problem, right?

**Comment by pragmadash** [comment]
I assume that you agree on this and we have nothing to fix here.
