### ISSUE TITLE
Research possible Webpack migration... again

### ISSUE THREAD

**Issue by pragmader** [catberry/catberry#271]
The last experiment a year ago was failed. Maybe nowadays it's slightly better. I see some benefits from this migration:
- hot reloading for debug mode
- dealing with resources (we don't need assets plugin anymore)
- built-in compilation and minification

But also, there are some concerns:
- how it substitutes server-side modules with browser-side versions?
- does it support the `browser` field in `package.json`?
- can it completely replace browserify?
- does it influence on the bundle size
- can you control the ES6 compilation and set some presets there

**Comment by reflog** [comment]
Regarding some of the concerns:
1. It does replace browserify completely
2. Bundle size is rather minimal (you can run https://github.com/robertknight/webpack-bundle-size-analyzer to see it's impact)
3. ES6 compilation is controlled by babel plugin, you can pass all babel settings to it
4. Regarding server-side/client-side substitution, I'm not sure to what you are referring, but it seems to work fine for people (https://github.com/mderrick/webpack-react-boilerplate/)

Hope this helps!

**Comment by pragmadash** [comment]
@reflog thanks for clarifying those points. The 4th is about Node.js modules, Browserify can replace server-side modules with their browser versions.

The most important thing so far is how we can continue using `browser` field in `package.json`. It's very important for the whole Catberry infrastructure. If we can't implement that support it's a red flag.

**Comment by reflog** [comment]
Oh. It does support that field:
http://webpack.github.io/docs/configuration.html#resolve-packagemains

**Comment by pragmadash** [comment]
Cool, I will try to integrate Webpack in Catberry 9 then.

**Comment by pragmader** [comment]
Started researching Webpack again and the question appeared. There loaders which are being used via `require` prefixes. But in our case the app is isomorphic and the same code is running on server as well where Webpack does not process the source code.

Does that mean we can't use loaders at all? Does it make sense migrating to Webpack then?

**Comment by pragmader** [comment]
No Webpack migration in near future. Catberry's build system is optimized for the framework very much, Webpack would never support the same level of integration.
