### ISSUE TITLE
Router and store with dashes

### ISSUE THREAD

**Issue by vizo** [catberry/catberry#272]
If your catberry store file is in directory which includes dashes (e.g. family-tree), router will not use it.
e.g. route: '/:page[Pages]/:itemId[family-tree/Tree]'
If i remove dash everything works.

It can be used with (-) in components and elsewhere, just in router not.

Also if you misspell store path it doesn't throw any error, like it does in templates "Store not found"

**Comment by pragmadash** [comment]
Thanks a lot for finding the bug.
Everything works fine with slashes. The problem is related to dashes only. Will fix it soon.

**Comment by vizo** [comment]
Ups sorry... i meant dashes, my bad! ;)

**Comment by pragmadash** [comment]
Will be solved by releasing #274
