### ISSUE TITLE
Improve routing subsystem

### ISSUE THREAD

**Issue by pragmadash** [catberry/catberry#274]
- [X] Write a real parser for routes (get rid of regexps and show parsing errors)
- [x]  Compile routes on back-end for the browser bundle
- [x]  Add support for route names, to generate URL for the route using specified parameters
- [x]  Show a warning when a store on the list does not exist (#272).

**Comment by pragmadash** [comment]
About the ID support:

```javascript
// we can define a route like this (adding an ID)
{
  id: 'page-changer',
  expression: '/:page[Page]/:subsection[Subsection]'
}
```

And then use a new $context method to generate a link for that:

```javascript
this.$context.getRouteURL('page-changer', { page: 'main', subsection: 'en' });
// it can be used for rendering links inside the app
```

This feature was requested by a couple of users and as soon as we implement a real parser for the expressions it will be easier to implement.

**Comment by vizo** [comment]
Named routes, that would be awesome! I was just going to ask you about that. :+1:
