### ISSUE TITLE
Component 'replace'

### ISSUE THREAD

**Issue by reflog** [catberry/catberry#275]
I'm wondering how can I do a 'replace' component? (Similar to replace directive in Angular).
Meaning, if I have component 
`<cat-test><header class='test'></header></cat-test>` I want it to render as `<header class='test'></header>` without `cat-test` wrapper. This is important, since alot of CSS framework depend on a certain order of DOM nodes, and wrapping them causes CSS to break..

Right not I have a workaround of pulling the class attribute into <cat-test> but it is ugly and exposes internal component details
Here's a small example and submit an issue:
https://github.com/reflog/catberry-bug-test1

Check 'document' and 'test' components.

Thanks!

**Comment by pragmadash** [comment]
There is no such option for rendering a component without its custom tag. This is how the framework identifies blocks on the page which must be re-rendered on a state change.

I took a look at your demo project and this behavior looks really weird to me. Looks like the CSS library you're using supports a header which is on the top level of the body only. But you still can use the component inside the header tag and it would work.

See the PR for that https://github.com/reflog/catberry-bug-test1/pull/1

Feel free to close this issue if you don't have any additional questions.

**Comment by reflog** [comment]
Thanks
