### ISSUE TITLE
Live reloading

### ISSUE THREAD

**Issue by reflog** [catberry/catberry#276]
I know this is currently not built in, but maybe it's something that should be mentioned in documentation, since it's rather easy to add:

1. To add server reload, install `nodemon` and change `debug-win` command to: `    "debug-win": "powershell -Command \"Start-Process -NoNewWindow node ./build.js; Start-Process -NoNewWindow -Wait  -ArgumentList '--watch server --watch build.js --watch routes.js  ./server.js' nodemon\""`
2. To add client side reload, install `express-livereload` and do the following:

In server.js, below 
`const app = express();`
add:
`var livereload = require('express-livereload');
livereload(app);`

In head.hbs, add:
`<script>document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] + ':35729/livereload.js"></' + 'script>')</script>`

Works pretty good for me!

**Comment by pragmadash** [comment]
Yeah, sounds good.

**Comment by reflog** [comment]
Would you like me to submit a PR for documentation?

**Comment by pragmadash** [comment]
@reflog it would be great, thanks!
