### ISSUE TITLE
Error for createComponent without attributesObject

### ISSUE THREAD

**Issue by reenko** [catberry/catberry#281]
Now we don't need have ID and I think we can create components without attributes.

I have a problem when call `.createComponent('cat-component')` but `.createComponent('cat-component', {})` - it's correct. What you think? 

```
DocumentRenderer.js:401 Uncaught (in promise) Error: Tag name should be a string and attributes should be an object
    at DocumentRenderer.createComponent
    at ModuleApiProvider.componentContext.createComponent

```

**Comment by pragmadash** [comment]
Agree, good point. Will fix it in next release.
