### ISSUE TITLE
Routes: regular expression - v: 8.4.1

### ISSUE THREAD

**Issue by dumperize** [catberry/catberry#295]
Если в routes добавить елемент с regular expression: 
```javascript
{
    expression: /^\/orders\/\d+/i,
    map(uri) {
        const matches = uri.path.match(/^\/orders\/(\d+)/i);
        return {
            order:{
                orderId: Number(matches[1])
            }
        };
    }
}
```
Ответом на запрос `/orders/1` будет `Cannot GET /orders/1`

При указании в package.json точной более ранней версии catberry
```javascript
"dependencies": {
		"catberry": "8.2.0",
                  ...
}
```
Ответом на запрос `/orders/1` будет полноценная страница со статусом 200.

**Comment by pragmadash** [comment]
А по какой причине вообще используете регулярные выражения? Просто этот способ маршрутизация это скорее на крайний случай, а не на повседневное использование. Была какая-то причина?

Про сам баг не спорю, надо исправить конечно.

**Comment by dumperize** [comment]
Для примера у нас есть набор routes вида 
```javascript
// путь: рубрика/подрубрика
// путь: рубрика/подрубрика/тег
// путь: рубрика/подрубрика/секция (video|sale|sovety|company)
// путь: рубрика/подрубрика/тег/секция (video|sale|sovety|company)
```
Все они отрисовывают одну типовую страницу. Для того чтобы не создавать кучу похожих правил маршрутизации, решили заменить одним правилом с регулярным выражением: 
```javascript
	{
		expression: /^\/([^\/\d]+)\/([^\/\d]+)\/?((?!video$|sale$|sovety$|company$)[^\/\d]+)?\/?(video|sale|sovety|company)?$/i,
		map: function (urlPath) {
			var matches = urlPath.path.match(/^\/([^\/\d]+)\/([^\/\d]+)\/?((?!video$|sale$|sovety$|company$)[^\/\d]+)?\/?(video|sale|sovety|company)?$/i);
			return {
				Rubrika: {
					rubrika: matches[1],
					podrubrika: matches[2]
				},
				Tag: {
					tag: matches[3],
					section: matches[4]
				},
				Pages: {
					page: "master-rubrika"
				}
			}
		}
	},
```

И на самом деле, мы посчитали все три способа задания routes равнозначными, и каждый может выбрать для себя удобный, мы не подозревали что регулярки это на крайний случай (они работают хуже?).

**Comment by pragmadash** [comment]
По моему мнению иметь несколько простых правил намного удобнее чем одну мегарегулярку.

**Comment by reenko** [comment]
Поддерживаю, удобнее, понятнее, но у нас накопилось ~40 правил и еще будут новые, сначала думал описать регулярными выражениями, но в итоге решил завести несколько файлов с правилами поделенными на логические блоки. (пока не делал)
