### ISSUE TITLE
Problems with patching attributes

### ISSUE THREAD

**Issue by reenko** [catberry/catberry#305]
![image](https://cloud.githubusercontent.com/assets/11948740/17853764/cd64c826-6898-11e6-9ddb-6feb6960dace.png)

When component state is changed from _feed_ to _feedBest_ we have a problem with update attributes.

**Comment by pragmader** [comment]
Found it here https://github.com/catberry/catberry/blob/develop/browser/DocumentRenderer.js#L255

We need to use `onBeforeElChildrenUpdated` instead of `onBeforeElUpdated`. I mixed them up. We have to add a test for this case then.
