### ISSUE TITLE
Jade package renamed to Pug and now deprecated

### ISSUE THREAD

**Issue by imShara** [catberry/catberry#314]
Just `s/jade/pug/`
https://github.com/pugjs/pug

**Comment by pragmader** [comment]
There is a package https://www.npmjs.com/package/catberry-pug on NPM which was created exactly because of this. The `catberry-jade` package is kept because of backwards compatibility only.

But I agree it would be a good idea to deprecate `catberry-jade` as well.

**Comment by pragmader** [comment]
I've created this issue to update CLI https://github.com/catberry/catberry-cli/issues/21

**Comment by pragmader** [comment]
Created https://github.com/catberry/catberry-hello-world-pug template for the CLI.
