### ISSUE TITLE
Drop IE <=10 support and extend new JavaScript features

### ISSUE THREAD

**Issue by pragmader** [catberry/catberry#319]
Since Babel 6.x it does not support IE <= 10 out of the box but we fixed it with the [8.0.4](https://github.com/catberry/catberry/releases/tag/8.0.4) release using custom transformation preset.

I think it's time to drop support for IE <= 10 and use the standard preset with all the upcoming features.

If you have any urgent need to have support for IE <=10 using Catberry please let me know.

**Comment by pragmader** [comment]
We have to come up with a list of Babel transformations according to the Node.js server-side JavaScript grammar. 
It includes [full ES6 support](http://kangax.github.io/compat-table/es6/) for versions >= 6.5 and >=7.6.
Also, partial support for [ES2016](http://kangax.github.io/compat-table/es2016plus/).

**Comment by pragmader** [comment]
We also can use https://github.com/babel/babel-preset-env and dynamically decide what to support.

**Comment by pragmader** [comment]
We're in a weird situation: we can't allow to use any preset because it would break the minification which is currently done by Uglify (because it does not support ES6). But we still can't use [Babili](https://github.com/babel/babili) because it's in beta.

So, we have to either [use Babili](https://github.com/catberry/catberry/issues/321) and ignore its beta state or keep the current preset by default which can't be overwritten by `.babelrc` currently.

**Comment by kalyanov** [comment]
IE11 usage is still 3.1% — https://www.w3schools.com/Browsers/browsers_explorer.asp
IE11 es6 support is only 11%  — https://kangax.github.io/compat-table/es6

It seems that babel-preset-env didn't give a significant advantage today. But it's a little bit risky to use babili beta version.

I think, we have to wait one of this:
- stable babili release
- uglify harmony release
- ie11 usage will drop at least to 1%

As it doesn't look like a breaking changes, we can use babel-preset-env later.

**Comment by pragmader** [comment]
@kalyanov at least we can use the standard Babel preset by default and ignore IE <= 10. It won't break anything except the support of these browsers.

We can switch to Babili later without breaking changes, I presume.

**Comment by kalyanov** [comment]
Oh, yes. IE 10 is dead :)
